### ISSUE TITLE
Feature request: Add support for specifying values for named query parameters

### ISSUE THREAD

**Issue by m-ahmadkhan** [minodisk/bigquery-runner#12] opened 2022-06-24 08:22 UTC
First of all, thanks for this awesome extension. I've tried it, and if it gets set-up for our work, it'll make our lives much easier.

Though, the only issue that I'm facing to set-up this extension is the lack of support for specifying query parameters. If the query to run has named query params in them, the extension should have the ability to ask for the values to use in their place.

Thanks again.

**Comment by minodisk** [comment] 2022-06-24 13:49
Thanks for your request 😄 
I understood the situation.

**Comment by minodisk** [comment] 2022-06-24 13:50
## How to reproduce

1. I write the following query and execute it:
```sql
SELECT
  word,
  word_count
FROM
  `bigquery-public-data.samples.shakespeare`
WHERE
  corpus = @corpus
  AND word_count >= @min_word_count
ORDER BY
  word_count DESC
```
2. Then I get the following error:
![image](https://user-images.githubusercontent.com/514164/175547074-f463f575-2ccd-4401-8658-e3298c6251d7.png)

## Docs
- [Named parameters  \|  BigQuery  \|  Google Cloud](https://cloud.google.com/bigquery/docs/samples/bigquery-query-params-named)

## Solutions
1. Add a command to be executed with parameters.
    - When the command is executed, a parameter input dialog appears.
2. Find named parameters when query is run.
    - When named parameters are found, a parameter input dialog appears.

**Comment by m-ahmadkhan** [comment] 2022-06-25 20:03
@minodisk I don't think there's an option on the BigQuery Web UI for this. But it'll be cool to have this feature.

**Comment by minodisk** [comment] 2022-06-25 22:30
@m-ahmadkhan 
Thanks for letting me know.
I'm doing some major refactoring right now and will try to implement this feature after that.

**Comment by minodisk** [comment] 2022-07-07 14:35
@m-ahmadkhan 
I added experimental support for parameters in [v1.1.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v110
).
I am not fully aware of how parameters are used, so there may be implementation omissions.
If you find any implementation omissions, please report them to me with a sample query.

![image](https://user-images.githubusercontent.com/514164/177800033-d8e6f9d0-5ead-432a-8fbd-41bfa92e2b59.png)

**Comment by minodisk** [comment] 2022-07-11 11:05
@m-ahmadkhan 
I've updated the experimental implementation to allow various types to be set as parameters in [v1.4.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v140).
The extension will ask you for the value of the parameter, and you must specify the value in JSON format.

![bigquery-runner-1657536115053](https://user-images.githubusercontent.com/514164/178248203-a24126dc-4ade-4e6f-93ae-200702edfa51.gif)

**Comment by m-ahmadkhan** [comment] 2022-07-18 09:34
@minodisk it's awesome. Thanks for all your efforts. I gave it a try, and it definitely unblocks me to use this extension. There can be further improvements in this feature, but as a v1, it's awesome.

- Improve finding the query parameters in the query to not include the commented query params.
- Ask for the value of a query param only once if the same param is used multiple times in the query.
- We can improve the UI to show a form instead of opening separate pop-ups for every query param.
- If a query is run multiple times, the previously entered values for query params can be stored in some sort of storage to pull those values again in the future runs.

I'll also try to submit PRs for some of the improvements in the near future.

**Comment by minodisk** [comment] 2022-07-19 01:07
@m-ahmadkhan 
Thanks for reviewing :wink: 

> - Improve finding the query parameters in the query to not include the commented query params.

I didn't take into account the query parameter in the comment. That's a bug.
I tried some SQL parsers to parse queries correctly, but it didn't work very well, so I'm writing a parser by myself.
#22 created.

> - Ask for the value of a query param only once if the same param is used multiple times in the query.

I also didn't take into account not asking the same parameter multiple times. I thought that was indeed true.
#23 created.

> - We can improve the UI to show a form instead of opening separate pop-ups for every query param.
> - If a query is run multiple times, the previously entered values for query params can be stored in some sort of storage to pull those values again in the future runs.

Sounds like it could be useful.

PRs are welcome 😄

**Comment by minodisk** [comment] 2022-07-19 14:51
@m-ahmadkhan 
#22 and #23 are fixed and released as [v1.9.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v190).
Give it a try.

**Comment by minodisk** [comment] 2022-10-17 15:36
Query parameters are persisted in [v1.15.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v1150) 😉 

Related to:
> If a query is run multiple times, the previously entered values for query params can be stored in some sort of storage to pull those values again in the future runs.

**Comment by minodisk** [comment] 2022-10-17 15:46
Combining popup into one seems to be difficult due to VSCode's API, so we will not tackle it now.

**Closed by minodisk** 2022-10-17 15:46 UTC
Labels: enhancement

**Comment by m-ahmadkhan** [comment] 2022-10-18 09:56
Thanks for working on it. I had started working on it, but I was just too busy to get it done.

Thanks again. This will help a lot.
